// ─── MODEL WEIGHTS (generated by build_drosspom_model.ipynb) ─────────────────
// No-odds CV accuracy:   62.9%  |  Brier: 0.2252
// With-odds CV accuracy: 67.8%  |  Brier: 0.2039
//
// Weights derived from XGBoost feature importances on 7,177 UFC fights (2010–2026)
// using time-series cross-validation. Platt calibration applied.

const MODEL = {
  // Feature weights (normalized, sum to 1)
  W_NO: {
    "win_streak_dif": 0.077696,
    "avg_td_dif": 0.068343,
    "sig_str_dif": 0.063872,
    "R_avg_SIG_STR_pct": 0.058393,
    "total_round_dif": 0.056274,
    "elo_dif": 0.055311,
    "B_avg_SIG_STR_pct": 0.048587,
    "loss_dif": 0.04606,
    "height_dif": 0.044978,
    "cardio_dif": 0.044775,
    "R_avg_TD_pct": 0.043259,
    "lose_streak_dif": 0.042474,
    "avg_sub_att_dif": 0.04195,
    "age_dif": 0.041496,
    "layoff_dif": 0.041283,
    "reach_dif": 0.03988,
    "B_avg_TD_pct": 0.039716,
    "ko_dif": 0.039261,
    "win_dif": 0.03834,
    "total_title_bout_dif": 0.036427,
    "sub_dif": 0.031623
},
  W_OD: {
    "odds_edge": 0.225237,
    "avg_td_dif": 0.048877,
    "cardio_dif": 0.043262,
    "sig_str_dif": 0.041812,
    "lose_streak_dif": 0.040835,
    "win_streak_dif": 0.040763,
    "height_dif": 0.040048,
    "R_avg_SIG_STR_pct": 0.040012,
    "avg_sub_att_dif": 0.039505,
    "elo_dif": 0.037475,
    "total_round_dif": 0.037059,
    "B_avg_SIG_STR_pct": 0.036546,
    "R_avg_TD_pct": 0.035271,
    "layoff_dif": 0.034885,
    "ko_dif": 0.033502,
    "age_dif": 0.033457,
    "B_avg_TD_pct": 0.032699,
    "win_dif": 0.032539,
    "loss_dif": 0.032233,
    "reach_dif": 0.031407,
    "total_title_bout_dif": 0.03131,
    "sub_dif": 0.031265
},
  // Platt calibration: p = logistic(platt_a * composite + platt_b)
  PLATT_NO: { a: 1.7225631998412525, b: -0.18753374136521064 },
  PLATT_OD: { a: 1.4008053209780686, b: -0.09263130924926194 },
  // Normalization scales (1 std of each differential feature)
  // Used to put all features on the same scale before weighting
  SCALES: {
    sig_str_dif:          15.8,
    avg_sig_str_pct_dif:  0.10,
    avg_td_dif:           1.4,
    avg_td_pct_dif:       0.23,
    avg_sub_att_dif:      0.7,
    reach_dif:            10.8,
    height_dif:           9.1,
    age_dif:              4.3,
    win_streak_dif:       1.4,
    lose_streak_dif:      1.0,
    win_dif:              4.4,
    loss_dif:             2.7,
    total_round_dif:      17.0,
    total_title_bout_dif: 1.4,
    ko_dif:               2.0,
    sub_dif:              1.4,
    elo_dif:              49.6,
    layoff_dif:           200,
    cardio_dif:           0.24,
    odds_edge:            0.30,
  },
};

// ─── PREDICTION ENGINE ────────────────────────────────────────────────────────
// Computes win probability for fA vs fB using XGBoost-derived weights.
// Two modes: no odds (default), and with odds (when user enters a betting line).
//
// Feature naming follows ufc-master.csv conventions so weights map directly:
//   sig_str_dif          = fA.ASL - fB.ASL  (avg sig strikes landed per min)
//   R_avg_SIG_STR_pct    = fA accuracy (positive for A)
//   B_avg_SIG_STR_pct    = fB accuracy (negative for A)
//   avg_td_dif           = fA.ATL - fB.ATL
//   etc.

const computeMatchupEdges = (fA, fB, oddsA = null, oddsB = null) => {
  const S = MODEL.SCALES;

  // ── Compute each raw differential ──────────────────────────────────────────
  const feats = {
    sig_str_dif:          ((fA.ASL ?? 0) - (fB.ASL ?? 0)) / S.sig_str_dif,
    avg_sig_str_pct_dif:  ((fA.ASP ?? 0) - (fB.ASP ?? 0)) / S.avg_sig_str_pct_dif,
    avg_td_dif:           ((fA.ATL ?? 0) - (fB.ATL ?? 0)) / S.avg_td_dif,
    avg_td_pct_dif:       ((fA.ATP ?? 0) - (fB.ATP ?? 0)) / S.avg_td_pct_dif,
    avg_sub_att_dif:      ((fA.ASA ?? 0) - (fB.ASA ?? 0)) / S.avg_sub_att_dif,
    reach_dif:            ((fA.REACH_IN ?? 0) - (fB.REACH_IN ?? 0)) / S.reach_dif,
    height_dif:           ((fA.HEIGHT_IN ?? 0) - (fB.HEIGHT_IN ?? 0)) / S.height_dif,
    age_dif:              ((fB.AGE ?? 30) - (fA.AGE ?? 30)) / S.age_dif,  // reversed: younger is better
    win_streak_dif:       ((fA.WIN_STREAK ?? 0) - (fB.WIN_STREAK ?? 0)) / S.win_streak_dif,
    lose_streak_dif:      ((fB.LOSE_STREAK ?? 0) - (fA.LOSE_STREAK ?? 0)) / S.lose_streak_dif, // reversed
    win_dif:              ((fA.WINS ?? 0) - (fB.WINS ?? 0)) / S.win_dif,
    loss_dif:             ((fB.LOSSES ?? 0) - (fA.LOSSES ?? 0)) / S.loss_dif, // reversed
    total_round_dif:      ((fA.TOTAL_ROUNDS ?? 0) - (fB.TOTAL_ROUNDS ?? 0)) / S.total_round_dif,
    total_title_bout_dif: ((fA.TITLE_BOUTS ?? 0) - (fB.TITLE_BOUTS ?? 0)) / S.total_title_bout_dif,
    ko_dif:               ((fA.KO_WINS ?? 0) - (fB.KO_WINS ?? 0)) / S.ko_dif,
    sub_dif:              ((fA.SUB_WINS ?? 0) - (fB.SUB_WINS ?? 0)) / S.sub_dif,
    elo_dif:              ((fA.ELO ?? 1500) - (fB.ELO ?? 1500)) / S.elo_dif,
    layoff_dif:           ((fB.DAYS_SINCE_LAST ?? 180) - (fA.DAYS_SINCE_LAST ?? 180)) / S.layoff_dif, // reversed
    cardio_dif:           ((fA.CARDIO_RATIO ?? 1) - (fB.CARDIO_RATIO ?? 1)) / S.cardio_dif,
  };

  const useOdds = oddsA !== null && oddsB !== null;
  let oddsEdge = 0;
  let oddsImplA = null, oddsImplB = null;

  if (useOdds) {
    const toImpl = (o) => {
      const n = parseFloat(o);
      if (isNaN(n)) return null;
      return n < 0 ? -n / (-n + 100) : 100 / (n + 100);
    };
    const rawA = toImpl(oddsA), rawB = toImpl(oddsB);
    if (rawA && rawB) {
      const total = rawA + rawB;
      oddsImplA = rawA / total;
      oddsImplB = rawB / total;
      oddsEdge = (oddsImplA - oddsImplB) / S.odds_edge;
    }
  }

  // ── Map features to the weight keys used in training ──────────────────────
  // NOTE: The model trained on R_avg_SIG_STR_pct (absolute) and B_avg_SIG_STR_pct
  // (absolute) as separate features. Here we combine them into a single differential
  // and distribute their combined weight.
  const W = useOdds ? MODEL.W_OD : MODEL.W_NO;
  const accCombinedW = (W.R_avg_SIG_STR_pct + W.B_avg_SIG_STR_pct) / 2;
  const tdCombinedW  = (W.R_avg_TD_pct + W.B_avg_TD_pct) / 2;

  const clamp = (v) => Math.max(-2, Math.min(2, v));

  // ── Group into display edges ───────────────────────────────────────────────
  const strikingScore = clamp(feats.sig_str_dif) * W.sig_str_dif
    + clamp(feats.avg_sig_str_pct_dif) * accCombinedW;

  const grapplingScore = clamp(feats.avg_td_dif) * W.avg_td_dif
    + clamp(feats.avg_td_pct_dif) * tdCombinedW
    + clamp(feats.avg_sub_att_dif) * W.avg_sub_att_dif;

  const physicalScore = clamp(feats.reach_dif) * W.reach_dif
    + clamp(feats.height_dif) * W.height_dif
    + clamp(feats.age_dif) * W.age_dif;

  const formScore = clamp(feats.win_streak_dif) * W.win_streak_dif
    + clamp(feats.lose_streak_dif) * W.lose_streak_dif
    + clamp(feats.win_dif) * W.win_dif
    + clamp(feats.loss_dif) * W.loss_dif;

  const expScore = clamp(feats.total_round_dif) * W.total_round_dif
    + clamp(feats.total_title_bout_dif) * W.total_title_bout_dif
    + clamp(feats.ko_dif) * W.ko_dif
    + clamp(feats.sub_dif) * W.sub_dif;

  const analyticsScore = clamp(feats.elo_dif) * W.elo_dif
    + clamp(feats.layoff_dif) * W.layoff_dif
    + clamp(feats.cardio_dif) * W.cardio_dif;

  const oddsScore = useOdds ? clamp(oddsEdge) * (W.odds_edge ?? 0) : 0;

  const composite = strikingScore + grapplingScore + physicalScore
    + formScore + expScore + analyticsScore + oddsScore;

  // ── Platt calibration ─────────────────────────────────────────────────────
  const P = useOdds ? MODEL.PLATT_OD : MODEL.PLATT_NO;
  const pA = 1 / (1 + Math.exp(-(P.a * composite + P.b)));

  const edges = {
    striking:   { raw: strikingScore,   label: 'Striking',    icon: '⚔️',  weight: W.sig_str_dif + accCombinedW },
    grappling:  { raw: grapplingScore,  label: 'Grappling',   icon: '🤼',  weight: W.avg_td_dif + tdCombinedW + W.avg_sub_att_dif },
    physical:   { raw: physicalScore,   label: 'Physical',    icon: '📏',  weight: W.reach_dif + W.height_dif + W.age_dif },
    form:       { raw: formScore,       label: 'Form',        icon: '📈',  weight: W.win_streak_dif + W.lose_streak_dif + W.win_dif + W.loss_dif },
    experience: { raw: expScore,        label: 'Experience',  icon: '🎖️',  weight: W.total_round_dif + W.total_title_bout_dif + W.ko_dif + W.sub_dif },
    analytics:  { raw: analyticsScore,  label: 'Analytics',   icon: '📊',  weight: W.elo_dif + W.layoff_dif + W.cardio_dif },
    ...(useOdds && { market: { raw: oddsScore, label: 'Market', icon: '💰', weight: W.odds_edge } }),
  };

  return {
    pA,
    pB: 1 - pA,
    composite,
    edges,
    oddsImplA,
    oddsImplB,
    feats,
    useOdds,
  };
};
