// AUTO-GENERATED by generate_source_manifest.py -- do not hand-edit.
// Per-module provenance tuples for every active v2 feature-source module
// (plus cardio/rankHistory/rankings, tracked even though they do not feed
// MODEL_V2). maxObservedEventDate is computed by reading
// the actual underlying source data -- never a file mtime, git commit date, or
// in-file header comment. See research/source_integrity_audit.md for the manual
// methodology this script automates.
// Re-run this script whenever fightersData.js / fightHistory.js / eloModule.js /
// cardioModule.js / rankingsData.js / rankingsHistoryData.js are regenerated,
// so the
// manifest stays current.

export const SOURCE_MANIFEST = {
  "manifestGeneratedAt": "2026-08-12T00:34:37Z",
  "generatorScript": "generate_source_manifest.py",
  "methodologyRef": "research/source_integrity_audit.md",
  "modules": {
    "fightHistory": {
      "file": "src/fightHistory.js",
      "feedsV2": true,
      "generatedAt": "2026-08-10",
      "maxObservedEventDate": null,
      "contentHash": "75a725cd4f7af93caeb4353fea74055272e2259c68a26490a44d8fc3a0590ee2",
      "generatorVersion": "update_fighters.py @ c29071dc9f8c4e56b6b4355ee158d50dd95e5a6f",
      "verificationMethod": "Parsed DATE column of ufc_event_details.csv directly (0 rows); maximum event date found = None. Cross-checked ufc_fight_results.csv, ufc_fight_details.csv, ufc_fight_stats.csv for window-period event names: zero matches. This value is NOT derived from any file mtime, git commit date, or in-file header comment -- see research/source_integrity_audit.md for the original manual methodology this script automates."
    },
    "fightersDataAggregates": {
      "file": "src/fightersData.js",
      "feedsV2": true,
      "note": "Feeds ASL/ASP/ATL/ATP/ASA (sig_str_landed, sig_str_accuracy, sub_attempts, td_landed, td_accuracy) and TR (rounds) -- the highest-weight non-ELO v2 features.",
      "generatedAt": "2026-08-10",
      "maxObservedEventDate": null,
      "contentHash": "ac80f4647cad1b9b8d54d7edf49f252b08dbccdf3faef10abb6b0d931b30534f",
      "generatorVersion": "update_fighters.py @ c29071dc9f8c4e56b6b4355ee158d50dd95e5a6f",
      "verificationMethod": "Parsed DATE column of ufc_event_details.csv directly (0 rows); maximum event date found = None. Cross-checked ufc_fight_results.csv, ufc_fight_details.csv, ufc_fight_stats.csv for window-period event names: zero matches. This value is NOT derived from any file mtime, git commit date, or in-file header comment -- see research/source_integrity_audit.md for the original manual methodology this script automates."
    },
    "elo": {
      "file": "src/eloModule.js",
      "feedsV2": true,
      "generatedAt": "2026-08-10",
      "maxObservedEventDate": null,
      "contentHash": "0cb60aee84bb6b2b40b2cb476c44e734f9706a96942246d022d285ebe80aa35d",
      "generatorVersion": "regen_elo.py @ d2c56b9807b020db7ccca7db333298b997dff5e0",
      "verificationMethod": "Parsed DATE column of ufc_event_details.csv directly (0 rows); maximum event date found = None. Cross-checked ufc_fight_results.csv, ufc_fight_details.csv, ufc_fight_stats.csv for window-period event names: zero matches. This value is NOT derived from any file mtime, git commit date, or in-file header comment -- see research/source_integrity_audit.md for the original manual methodology this script automates. NOTE: eloModule.js's own header comment claims coverage \"through Jul 2026\" -- this is misleading relative to the verified underlying data and should not be trusted; regen_elo.py reads only ufc_fight_results.csv + ufc_event_details.csv, identical to the fight-history/fighter-aggregate sources above."
    },
    "cardio": {
      "file": "src/cardioModule.js",
      "feedsV2": false,
      "note": "Does not feed MODEL_V2 (no path into computeLogisticProb's 16 features, confirmed in research/source_integrity_audit.md). Tracked here for future model versions that might use it.",
      "generatedAt": "2026-04-13",
      "maxObservedEventDate": null,
      "contentHash": "7025f1f440bbf01c15731cc40e65521e50635902ee482536cd07a412738b788c",
      "generatorVersion": "unavailable -- no cardio-generation script found in repo",
      "verificationMethod": "INDETERMINATE: no generator script present in the repository, and no per-fighter date field is embedded in the shipped artifact itself, so maxObservedEventDate cannot be independently verified the way the Greco-CSV-backed modules above were. The file's own header comment self-reports \"fetched 2026-04-14\" -- this is NOT independently verified and should not be treated as authoritative."
    },
    "rankHistory": {
      "file": "src/rankHistory.js",
      "feedsV2": false,
      "note": "Does not feed MODEL_V2 (no path into computeLogisticProb's 16 features, confirmed in research/source_integrity_audit.md). Tracked here for future model versions that might use it.",
      "generatedAt": "2026-08-10",
      "maxObservedEventDate": "2026-03-12",
      "contentHash": "9a706f356ef41fa68b605dd9c52740dd370eda014dfb747b0cb8bdc6313ba244",
      "generatorVersion": "regen_rankhistory.py (untracked in git -- present on disk, no commit history, no recoverable version)",
      "verificationMethod": "Raw source UFC_rankings_history.csv is not present on disk, so maxObservedEventDate is instead the maximum YYYYMMDD date literally embedded in the shipped rankHistory.js artifact's own HISTORICAL_RANKINGS data -- a defensible proxy (the artifact cannot reflect dates its regeneration process never saw), but distinct from the direct-CSV verification used for the three modules above."
    },
    "rankings": {
      "file": "src/rankingsData.js",
      "feedsV2": false,
      "inProductionBundle": true,
      "note": "Current official rankings feed fighter-profile/UI rank badges only. Runtime artifact: this is the only rankings file in the production dependency graph. Historical series live in the separate rankingsHistory module below.",
      "generatedAt": "2026-08-07T18:49:33Z",
      "maxObservedEventDate": "2026-08-04",
      "contentHash": "48524131c5d78b0adc80d83fe27a2ef7c365c124f66eddab11e17487f7df41d0",
      "officialSnapshots": [
        "2026-08-01-meta.json",
        "2026-08-04-media.json"
      ],
      "generatorVersion": "scripts/update_rankings.py @ d8655dff1373d5b4286e4b6881957376c6ebf8aa",
      "verificationMethod": "Read directly from the generated artifacts and the committed history cache, all produced by scripts/update_rankings.py and regenerating byte-identically from the same inputs. upstreamContentSha256 is the SHA-256 of the Kaggle CSV the cache was built from. No git commit date, file mtime, or header comment is consulted, and a missing artifact, cache or snapshot set is a hard failure rather than a silent fallback."
    },
    "rankingsHistory": {
      "file": "src/rankingsHistoryData.js",
      "feedsV2": false,
      "inProductionBundle": false,
      "note": "Historical divisional rankings. RESEARCH ARTIFACT: no runtime consumer and no model consumer -- neither the deprecated v1 engine nor the frozen 16-feature MODEL_V2. Kept out of the browser bundle; enforced by src/domain/rankings/__tests__/boundary.test.js (import graph) and scripts/verify-bundle.mjs (emitted assets).",
      "generatedAt": "2026-08-07T18:49:33Z",
      "maxObservedEventDate": "2026-08-04",
      "contentHash": "387363b7f1fda0f51757fd778ff969ce9fffe1d34d3c870437977db5e36003a3",
      "historyCacheSha256": "4f245240e2b53ee088d82f861aa0a718aef9f62bf15d62eb434d4628b3b6b3ad",
      "upstreamContentSha256": "2d27b34e64372520e9170cc30f1d1c59e795d046b6726de89db95b9535db9858",
      "upstreamVersion": 49,
      "historyUsedThrough": "2026-06-18",
      "generatorVersion": "scripts/update_rankings.py @ d8655dff1373d5b4286e4b6881957376c6ebf8aa",
      "verificationMethod": "Read directly from the generated artifacts and the committed history cache, all produced by scripts/update_rankings.py and regenerating byte-identically from the same inputs. upstreamContentSha256 is the SHA-256 of the Kaggle CSV the cache was built from. No git commit date, file mtime, or header comment is consulted, and a missing artifact, cache or snapshot set is a hard failure rather than a silent fallback."
    }
  }
};
